# Generated by Django 3.2.4 on 2021-06-20 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_comment_author'),
        ('posts', '0014_auto_20210620_1351'),
    ]

    operations = [
    ]
