# Generated by Django 3.2.4 on 2021-06-23 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_auto_20210623_0154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='disklikes',
            new_name='dislikes',
        ),
    ]
