# Generated by Django 3.2.4 on 2021-07-01 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0021_post_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date_posted']},
        ),
    ]
