# Generated by Django 3.2.4 on 2021-07-02 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0022_alter_post_options'),
        ('posts', '0022_auto_20210702_0437'),
    ]

    operations = [
    ]
