# Generated by Django 3.2.4 on 2021-07-03 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0023_post_dislikes'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='followers_count',
            field=models.BigIntegerField(default='0'),
        ),
    ]
