# Generated by Django 3.2.4 on 2021-07-05 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0024_profile_followers_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorites',
            field=models.ManyToManyField(blank=True, null=True, related_name='fav', to='posts.Post'),
        ),
    ]
