# Generated by Django 3.2.4 on 2021-07-09 02:03

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0030_hashtag'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashtag',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='post',
            name='mentions',
            field=models.ManyToManyField(blank=True, related_name='mentions', to=settings.AUTH_USER_MODEL),
        ),
    ]
