# Generated by Django 3.2.4 on 2021-07-10 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0032_alter_hashtag_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mention_count',
            field=models.BigIntegerField(default='0'),
        ),
    ]
